package:
  name: intake-splunk
   version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - jinja2
  run:
    - intake
    - python
    - requests

test:
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
    - coverage
  commands:
    - py.test --verbose --cov=intake_splunk tests

about:
  home: https://github.com/ContinuumIO/intake-splunk
  license: BSD
  license_file: LICENSE
  summary: |
    Splunk plugin for Intake
